[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "697f45ca0be4369173bd3f5d86e30a746919be10"
os = "macos"

    [[aws_c_event_stream.download]]
    sha256 = "c6ce4c5f343c71354234ee3a5c04a8eb562213bcfbfab4a0f37ee471cfb460ad"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.9+0/aws_c_event_stream.v0.5.9.aarch64-apple-darwin.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "5316366a52af35ad502bdae49511388695087c80"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "4137fff7c6b3f998cde35c82e4e7e635808241b32044ade9ec31fbe032a6f4d2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.9+0/aws_c_event_stream.v0.5.9.aarch64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "32d3420df0b6fec103a95f180af2b473020c9d68"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "21c33d30ddd6544835d6e1cb0bf51a130b2d19741616c46febeffc705e06352a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.9+0/aws_c_event_stream.v0.5.9.aarch64-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "ee2ed78478bd79bb668fff197abc8b96b9fb352f"
os = "freebsd"

    [[aws_c_event_stream.download]]
    sha256 = "6b92f271bb356b19b367df0250a0fe83464e121e0c3150680618f88a7b80e3e1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.9+0/aws_c_event_stream.v0.5.9.aarch64-unknown-freebsd.tar.gz"
[[aws_c_event_stream]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6821e603c07d7d110e5e0ac8280747724fe15b84"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "0dad65ea726d79b0e654b2411089d1c7175ce5b04672f3785fe18d77bd0989cb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.9+0/aws_c_event_stream.v0.5.9.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "16514d966c62cb0ee4eb9a0d5fc393c7e137a632"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "f7a7ce4474269028796f4b085ee9a96569db4b7406ed2dd5a95c4a3dc22f9dab"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.9+0/aws_c_event_stream.v0.5.9.armv6l-linux-musleabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2904df5146c42ccdc7456da039bd55486768a782"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "9147037a9923552af0c388d410e1f5cda9e79945bfb56432506d33227fc492a1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.9+0/aws_c_event_stream.v0.5.9.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ee94796b598541e295ff29f59c0d7adbbed4cc42"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "f5156e01448eb3332825fe92258d5141eb59186fc2aeeebaf6a8a593a30c3d10"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.9+0/aws_c_event_stream.v0.5.9.armv7l-linux-musleabihf.tar.gz"
[[aws_c_event_stream]]
arch = "i686"
git-tree-sha1 = "d023991f7caad33be07cdb2efc962e746ed9447d"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "1927c66dccc92c9aaea01f0c08267c848248eea1ee84d9c0b0db55362b464d38"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.9+0/aws_c_event_stream.v0.5.9.i686-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "i686"
git-tree-sha1 = "8a572503daadd121f8beb7865c8a684916e635b3"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "94b278078d608bc05e93831b6c334d606bad57cf158f5fbb14f2a41628bcfc29"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.9+0/aws_c_event_stream.v0.5.9.i686-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "powerpc64le"
git-tree-sha1 = "44fff37be7d762c8deeadc774e1c485ed4a1db72"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "3ac308576cb0e03fbfa1fcf37970332dd6bcc322ce5935e37c22e3c725273c96"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.9+0/aws_c_event_stream.v0.5.9.powerpc64le-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "riscv64"
git-tree-sha1 = "5c6e49f81cf19fbdeb6d17b560a50c5f43d97d32"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "3d2577c99f0ee50e203b8c10ac902f625e81536e48194bea5239c683f51cab9f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.9+0/aws_c_event_stream.v0.5.9.riscv64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "d3c9ae5eecd17bf5294acebc138405a8664c5158"
os = "macos"

    [[aws_c_event_stream.download]]
    sha256 = "3dcfa9bb2fa55bef59545db698f649a11345e6f4dfd1b59c26e966ce44a4f382"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.9+0/aws_c_event_stream.v0.5.9.x86_64-apple-darwin.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "f3042f2b6715c00d7ec0dd548aa7604111e9cef5"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "bdcb8ec9e76d3cbe50064055730a3a656eb18cf15691c35fd8c0968fd28cf622"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.9+0/aws_c_event_stream.v0.5.9.x86_64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "e5927d4d8ac5306e4f65fdde78ddbd52d8f4527a"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "ef5a2f3e9b08808b91166b841654adeba1b6f8c9dbee27b5474796ca8e625b79"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.9+0/aws_c_event_stream.v0.5.9.x86_64-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "0cba3f14943e81a160fb8d45a3ac2e2f7e51a337"
os = "freebsd"

    [[aws_c_event_stream.download]]
    sha256 = "3bb76f9dc63e569879e38d95bb29c09bd8f917d02efb1f0cc719fe85ef84d989"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.9+0/aws_c_event_stream.v0.5.9.x86_64-unknown-freebsd.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "6c55cb08adc5d5cdc9ec5e6687d180acbce6e8ce"
os = "windows"

    [[aws_c_event_stream.download]]
    sha256 = "b1607d6fb2cb3bbb9ea7744516f45b0fb8b7e2ba6657fd0eefb68487071c73c4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.9+0/aws_c_event_stream.v0.5.9.x86_64-w64-mingw32.tar.gz"
