[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "f6dcca8fbaffe17edce4486b00a838060e3fc1cb"
os = "macos"

    [[aws_c_event_stream.download]]
    sha256 = "c6ccd655627ae5ef24cfaafb8993d1e0871213035da8f9e5affec5886796731a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.4+0/aws_c_event_stream.v0.5.4.aarch64-apple-darwin.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "a2319829f3da5ddaf638f084bb6ab60291947453"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "9c98143c2b2a99f6f9498b5c5148bba3c8f65b94c5574924dc1e9995864f6aeb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.4+0/aws_c_event_stream.v0.5.4.aarch64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "27151a7e29555d778aeca6b9e9891706f528db86"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "7ae31be4ab97cf9b6af4e7819c1be7f764c63bd1dba48de23c783283e4ee9b1b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.4+0/aws_c_event_stream.v0.5.4.aarch64-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "94af4885e73e914b0ffc92e9546e1f55c197f570"
os = "freebsd"

    [[aws_c_event_stream.download]]
    sha256 = "20fead0d80bd3c28f435f094925cfc928311159e04b6d64e2777863cfc0263c1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.4+0/aws_c_event_stream.v0.5.4.aarch64-unknown-freebsd.tar.gz"
[[aws_c_event_stream]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "809cff31d363b779a8f264baddedfba240c49811"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "9fbdaafc4f9cc7636489f21da105c5ec41babac103a24101952a8e085a81c930"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.4+0/aws_c_event_stream.v0.5.4.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eae6e149b74827cbc86c6014131f073f1aae2517"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "d54dbf31758cb1b71e1e096ea20a6870ff90e2c5f72f9efac449fbcd2ddb3eaf"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.4+0/aws_c_event_stream.v0.5.4.armv6l-linux-musleabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a8127c512f94d7b60e3c310154b003d06546779f"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "bd26151264d737d0e0f7409df0ffd2cee3f097bb50cf7d809a6e64d9acc73fb1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.4+0/aws_c_event_stream.v0.5.4.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1daa4ead5b9689391d2ffb6bb368f91ef3083ac6"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "3233b66d37697be54361b2e0bab8159c9f74cc594a5fbdd4e6e2ceda0160f498"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.4+0/aws_c_event_stream.v0.5.4.armv7l-linux-musleabihf.tar.gz"
[[aws_c_event_stream]]
arch = "i686"
git-tree-sha1 = "aaeae7e41fbf6b701b7c105ba3fd2bbc5ccf52e9"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "a6af49a0cd947e2ba2a8ee2f175aee8659dfad1555f0f89f5f552052455103fc"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.4+0/aws_c_event_stream.v0.5.4.i686-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "i686"
git-tree-sha1 = "98470700cff7f61c6a3d6a5333ac4bbdf26d1988"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "80d8e3bef897810d3b497ab2617367730e655d985a06536eb15421937df040ba"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.4+0/aws_c_event_stream.v0.5.4.i686-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "powerpc64le"
git-tree-sha1 = "d75e3b3778cb41b7ee3b60e28a759e84b2e0519b"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "9e9ab6ac86cb0cec8ee4504c67880848bff0cc8ba35fcdb8472a8f90e19f79ed"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.4+0/aws_c_event_stream.v0.5.4.powerpc64le-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "riscv64"
git-tree-sha1 = "f8c181aeae0263b7f906da8a07bc29e4f03e3c9a"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "f08835cc6636d7e9a4678964f5dfc1a45cb20fe6b0becf71401a6f9798bd95ae"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.4+0/aws_c_event_stream.v0.5.4.riscv64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "414ef23acac55f273916ef10cbc65d7524e14a61"
os = "macos"

    [[aws_c_event_stream.download]]
    sha256 = "30daac84351b7dbe51e3d5ba5defdf0a63b917570e29f7af7eddc1668a31922c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.4+0/aws_c_event_stream.v0.5.4.x86_64-apple-darwin.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "c2555d414938819797553b2525388cf392890f51"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "77aa55e3ee6a966f99efed85a7719cc2b7777cacf7f53175e5e7b4773a2963df"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.4+0/aws_c_event_stream.v0.5.4.x86_64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "f228c29bfd18fa677c7ff2cb2b4bb0e1ec852655"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "cc12f97cdef1dda904a55950faa67694b4389527397b442dc9e1412cbbd76e9e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.4+0/aws_c_event_stream.v0.5.4.x86_64-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "0dc40b230ba617a416fbbadef6bdeadb26835254"
os = "freebsd"

    [[aws_c_event_stream.download]]
    sha256 = "738fee4f12d2e97a74f5da2d609c46ebf527d3eac6349766f92fd6473cd62672"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.4+0/aws_c_event_stream.v0.5.4.x86_64-unknown-freebsd.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "9f5edbdad895e64541833c73ac40fc95706c1e5a"
os = "windows"

    [[aws_c_event_stream.download]]
    sha256 = "59d1c462dc092de71f00e0161511c0365f559c88e21ec9d42ed02290c3990d4f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.4+0/aws_c_event_stream.v0.5.4.x86_64-w64-mingw32.tar.gz"
