[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "6759bdfcb731552a4b93488328a51885f1b47d83"
os = "macos"

    [[aws_c_event_stream.download]]
    sha256 = "901caf3d901a77164f4af5bf00b41faf3493918b63aaeb4df48f287b3e3b5e70"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.8+0/aws_c_event_stream.v0.5.8.aarch64-apple-darwin.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "b74cff9024d60d9e30a53c15e1e2de02cf171338"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "97e0e19d1584c9f2aba76d33d6288d99e1b7fe096d900cbafa47d2e8f74ad644"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.8+0/aws_c_event_stream.v0.5.8.aarch64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "429ee15f3752a72e18bd52db2a0fcb79830dafc2"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "d8fada5443e93228fe31b98c67c7d4fd5c5a4c2a8904e33cd5bc61a0f28a6381"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.8+0/aws_c_event_stream.v0.5.8.aarch64-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "c6347904c828acaeccbf24827e89da90513d007e"
os = "freebsd"

    [[aws_c_event_stream.download]]
    sha256 = "feba0d44fb4c030dbd7bf1bb5fab0f2d4ed4ec9e1c63b34c72be783e7e06a676"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.8+0/aws_c_event_stream.v0.5.8.aarch64-unknown-freebsd.tar.gz"
[[aws_c_event_stream]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e69d6a4324d0c8b30bb2d369f0e1374ca7a597f0"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "ff320e044f0b5d1d5ffb36fb33af188cad7e84990a81f074436f63b274988e6f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.8+0/aws_c_event_stream.v0.5.8.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "56ebc491a8bf41988c3a6a2bd953e3cffd5e72ec"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "ba72d8ee1e09373dbc8ca5cdec2f7cec2b992c3d990eeedbe3e8ceb57dbac4cb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.8+0/aws_c_event_stream.v0.5.8.armv6l-linux-musleabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6125a2d0807b22904705b02bfe66ab490731d359"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "086f21e7f6fd8a2c7bdf89bf87366ad073b4f2e6f53f4c87b2abc820a4bafef2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.8+0/aws_c_event_stream.v0.5.8.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b8d84b62659321c81b671fcca824fc1004a5374f"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "1ea02fc6c57fedbc04de08fa86712f80afde55f606aead0c16ad986cae5eb4c2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.8+0/aws_c_event_stream.v0.5.8.armv7l-linux-musleabihf.tar.gz"
[[aws_c_event_stream]]
arch = "i686"
git-tree-sha1 = "7f1883a20307350f28157a185a36cd6d0cd651b4"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "0905481f86fc77e8662b074085c3ceb200c47a4dbdee69129fa62d789359809a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.8+0/aws_c_event_stream.v0.5.8.i686-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "i686"
git-tree-sha1 = "30c214868f68edcda972e96b18dd90ebc8ae7c59"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "db4d9d78cf16ddb1a5c655cead64272e45413ea1cadefa0564fb5a906ca1be2c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.8+0/aws_c_event_stream.v0.5.8.i686-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "powerpc64le"
git-tree-sha1 = "7635b45fd655897ecb391314e5e8a43028a7f0be"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "442f6b08cfeda4f6560ff5b7cdfcf4acfce447202f8b189a87fd7f88dd3d0302"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.8+0/aws_c_event_stream.v0.5.8.powerpc64le-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "riscv64"
git-tree-sha1 = "714b75468950061e06a03ad9720dfa39c145ad18"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "ae9863ad344c999443de66787b131d3ef7d0028c4a0632de154c4e0edc6487f0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.8+0/aws_c_event_stream.v0.5.8.riscv64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "df103fbbec671db0fe7572cb3cd40a1b8e10dd12"
os = "macos"

    [[aws_c_event_stream.download]]
    sha256 = "72080a9f25f0371d76096479f7145adcf7fd4a83b6689b27576e2b290f06c84b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.8+0/aws_c_event_stream.v0.5.8.x86_64-apple-darwin.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "60be0f3fdc619995117ffafad374a80a0f7ceb3d"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "c23cd21b0c2ab1555df0bf75919115e082c6c9446a071209ecf108e27277fb79"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.8+0/aws_c_event_stream.v0.5.8.x86_64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "174951521e4a1c48522628bf7338c03201fbf119"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "6c2c613877bc0b308b4fe430fbd8b055d5aaedf69cf60cd60cd417afa136f9e6"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.8+0/aws_c_event_stream.v0.5.8.x86_64-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "0d4acb7457784df3134afd0037a7c243fd24fc06"
os = "freebsd"

    [[aws_c_event_stream.download]]
    sha256 = "fe9026f3afaab85e9155df87f329b7c1229cc0fda1bcbbf11ced8bc205510796"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.8+0/aws_c_event_stream.v0.5.8.x86_64-unknown-freebsd.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "034514a0e55e11d6a61c6587e79f84d03f43a4bf"
os = "windows"

    [[aws_c_event_stream.download]]
    sha256 = "fb4d895118a5b9212d768ee19a2b5a1222788a7946c99d8bca9f94782d9891fc"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.8+0/aws_c_event_stream.v0.5.8.x86_64-w64-mingw32.tar.gz"
