[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "930d9c8ec52640dd01af1f3a974816aeceb6ecbd"
os = "macos"

    [[aws_c_event_stream.download]]
    sha256 = "703885b8eb2a1b8b24f0063d974ab56a069ab3b13ce84941d45404138593c81d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.3+0/aws_c_event_stream.v0.5.3.aarch64-apple-darwin.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "bf08586ab3c2650393fcbe80c824919de6ed2b6e"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "d78b412a6ea81d700821c894d71fc46d0c900fda7d8ae58fd0293b5d39b65e67"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.3+0/aws_c_event_stream.v0.5.3.aarch64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "d97d17431dea51dd04177127c181202b6a7e9d9f"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "67dfa70c5e0c1dafc198a42d49c1764012bf1b74ab9989bcb0ccec981e4de385"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.3+0/aws_c_event_stream.v0.5.3.aarch64-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "00a7562833cd393debe5678ddc84ae241d3da553"
os = "freebsd"

    [[aws_c_event_stream.download]]
    sha256 = "d73117ebaf1fca2c50de3762fbb0ae3f2b1722439150c878b9ae729ca54a6709"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.3+0/aws_c_event_stream.v0.5.3.aarch64-unknown-freebsd.tar.gz"
[[aws_c_event_stream]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "35ac4f5f0eea90f101b0a3ac57bcd0d173c2d8be"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "483aaee05bab7591f9a9b6dc8e4a61782478f5e9214265e20dc19e391944d2a4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.3+0/aws_c_event_stream.v0.5.3.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "247c5af3a39ab969bdb76c363febdd95f7f510ac"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "2359508bebb5ea8fa8a3b4fb5cbf22da1bc1c4a19095bf3e60fcae8784ab8787"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.3+0/aws_c_event_stream.v0.5.3.armv6l-linux-musleabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ba66ad02657cdcb27deb02993f4a036e37564ef2"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "de37d384a14c5b69c4a353645ad1ebd1833536f0e27a149d0301834422067d66"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.3+0/aws_c_event_stream.v0.5.3.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "516df5cf21bfb351836bd593a9eda4eed7c128fb"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "a34d6609f1db0429cc9d4fb82d472d30da344b3e74ecc696b9510bb9f89e8d77"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.3+0/aws_c_event_stream.v0.5.3.armv7l-linux-musleabihf.tar.gz"
[[aws_c_event_stream]]
arch = "i686"
git-tree-sha1 = "b8e48097dea40f2f0c011c855084da7073a46133"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "6e0f6cc80705ccd352e732ebf8c80f7599af64aa2a729436cb7502448a2537bd"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.3+0/aws_c_event_stream.v0.5.3.i686-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "i686"
git-tree-sha1 = "88401f1e7eea912840f352aa45ec261c214d121d"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "a6f2b952e79408ee0a308a4e1995c17790608a04d89f076fc117dfaa18b60b09"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.3+0/aws_c_event_stream.v0.5.3.i686-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "powerpc64le"
git-tree-sha1 = "7038c9ce32ae7aa67fc91bd55add29cf164241d5"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "fc3b25038cb7a780e979a890ce6ec3ee34ac3cfb08c0a5c835200392b273a83a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.3+0/aws_c_event_stream.v0.5.3.powerpc64le-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "riscv64"
git-tree-sha1 = "fc4ad0e816450283ca7ab50ff5907677055f2ed0"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "a816107e6b2aae6f6f4a1d444d68d4b347031648d3ead213c9406f5ccabcb28b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.3+0/aws_c_event_stream.v0.5.3.riscv64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "bea18e59d38daa7562efbea01549ab01e7f93bb6"
os = "macos"

    [[aws_c_event_stream.download]]
    sha256 = "8eb9f58a5f240d494b7c9cd6437690c9b6d705cae9950eaf210416523c756bec"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.3+0/aws_c_event_stream.v0.5.3.x86_64-apple-darwin.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "676f4ec2a95741b771c52a04c6f277d263c5e431"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "3d3484941cc3121bc64aa3d28e0966df0022da514036fd5c93fd403da75c8803"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.3+0/aws_c_event_stream.v0.5.3.x86_64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "6b88f0ee863f2ff6b9240d837695dabf60dffcda"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "b15e9486024abf82190e0a2deea39838e6c0915002e087ea3eaa49187e8bcd7c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.3+0/aws_c_event_stream.v0.5.3.x86_64-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "9d53371fa799e3166410ff18c810dafd52178dd1"
os = "freebsd"

    [[aws_c_event_stream.download]]
    sha256 = "f62d277099e292972195986e1a8fec44df065f1d462b5b3bf5f9c48885e5a829"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.3+0/aws_c_event_stream.v0.5.3.x86_64-unknown-freebsd.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "c2a5fea759414d213f3eb6bd155be46cd3194fcf"
os = "windows"

    [[aws_c_event_stream.download]]
    sha256 = "1eb0c2b453450445f9e360637d6a81955c92db0cef51bc016e7fd55e9ab126d8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.3+0/aws_c_event_stream.v0.5.3.x86_64-w64-mingw32.tar.gz"
