[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "fa438128d88d6b29b79f6b66121dc0213b7c232d"
os = "macos"

    [[aws_c_event_stream.download]]
    sha256 = "f85d3c27c635802bec48e5e47216df6003353ee14ce79ccd975df9727def2b09"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.3.2+0/aws_c_event_stream.v0.3.2.aarch64-apple-darwin.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "9ecfa14a71363aff5887dddf9f9ee18d63c7ad40"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "147241bb2d06681bc2706be996a678212216f20670bd16875b6006cbb0285fd4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.3.2+0/aws_c_event_stream.v0.3.2.aarch64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "906fd6292deafa5749215e1c22c55e85e6e8e4b9"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "d1fdddd0ae4cd4ca265e960b5192b2980638aefacd2fc19183271c94bfba24e9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.3.2+0/aws_c_event_stream.v0.3.2.aarch64-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9b582393c21237ea654dc5c80779362cff487a59"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "f6d6278fedef9e707d7034a3035536fd5c45320dcd3a1cb41bf3b4416330ed64"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.3.2+0/aws_c_event_stream.v0.3.2.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c6980b227523a3e4907367b5f00aa4ee8e4708b6"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "546c0cb9bc93a903188bf3f0d8dd28875fc8b9a2de84a46e498f6f2796d7cc0d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.3.2+0/aws_c_event_stream.v0.3.2.armv6l-linux-musleabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7c59ed8bb0597ad5898581ba767297f0ab885852"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "5cc5f783400b1b291219dc5771ad23dd7761f9cb13ddc45a8128bff66516bbec"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.3.2+0/aws_c_event_stream.v0.3.2.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "237acd9a41a44ded8971c0db20afee754d0e77cb"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "1eb91d5d73a2ecf9c6234a920f77904df9d454bfa2e6f956e8aff0872065ad53"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.3.2+0/aws_c_event_stream.v0.3.2.armv7l-linux-musleabihf.tar.gz"
[[aws_c_event_stream]]
arch = "i686"
git-tree-sha1 = "b782e49745630b122dd4f5a207b8ce2dbff5a43b"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "871f521590effc73e8095919825b76a7c48d599cf74cbaafdd226ea93bc5c5fd"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.3.2+0/aws_c_event_stream.v0.3.2.i686-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "i686"
git-tree-sha1 = "5773a6a1b829769e87e356e47722d9c14c37522c"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "5daf8304712667c402c2fc86fb6255e5db421c557d24fe4753bcb378eb8371d0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.3.2+0/aws_c_event_stream.v0.3.2.i686-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "powerpc64le"
git-tree-sha1 = "218ac8f29c7ca2992b8b96881aec6e762c830129"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "bdd537d2735ab6d3fd10edd45248c88d606b69856babb1a7a3df7c5701b5688d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.3.2+0/aws_c_event_stream.v0.3.2.powerpc64le-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "e57e61d5cf54fd395b342a1cdf33395c3b55233a"
os = "macos"

    [[aws_c_event_stream.download]]
    sha256 = "b9b64d5e0f83cb89e343bbef460faa3724137123d84e86482018b6949db16170"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.3.2+0/aws_c_event_stream.v0.3.2.x86_64-apple-darwin.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "4d65853813ab871a869e1108c5937252e652aec3"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "84d7444453b3b878fb13307d6447b096f9eb37636486dcf3a6e888de0cb38a1f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.3.2+0/aws_c_event_stream.v0.3.2.x86_64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "7cb254134847793ac698cb97122d2285a2823423"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "20300e2899ba06ec96086425d0baa103e7e411e5e12539da3f160c9d7c481431"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.3.2+0/aws_c_event_stream.v0.3.2.x86_64-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "7f4a56ee2c78c8bd83ec0ba0358d064b09edb472"
os = "freebsd"

    [[aws_c_event_stream.download]]
    sha256 = "7f9c791847108888f59c4f313c9dd33d2dbcc2e7dee2992e9f64cb77d73ec845"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.3.2+0/aws_c_event_stream.v0.3.2.x86_64-unknown-freebsd.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "79e86fd91265bac29f45956077c06f2cc550f42d"
os = "windows"

    [[aws_c_event_stream.download]]
    sha256 = "2ec407056e919ad997c10d99790c69756dd8df1a2ae9e4170f9ac9af52725d16"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.3.2+0/aws_c_event_stream.v0.3.2.x86_64-w64-mingw32.tar.gz"
