[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "8ee84872e5fba0be46b0f7db29419933d3647372"
os = "macos"

    [[aws_c_event_stream.download]]
    sha256 = "9d906240f39d781864376838ca4f0f71fff8e347cdddc7aec5ad88d3f67f3078"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.7+0/aws_c_event_stream.v0.5.7.aarch64-apple-darwin.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "71456fc54e94a4905d77fe71f56080b64ee68f0f"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "60cb8e3682c0dff019b72346b372bf4d4b244d39094ad0ad085ff5ad6358de3b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.7+0/aws_c_event_stream.v0.5.7.aarch64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "736fb0e6408c4fa2ad6eb448edef03cef60b4af4"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "3efc17e2bf7e53acaeddedf49bf602fa19a40c884064ac01534b4e3faa1ce62d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.7+0/aws_c_event_stream.v0.5.7.aarch64-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "56061e9bda0c157b66e5714cfc18cbbc698e88e6"
os = "freebsd"

    [[aws_c_event_stream.download]]
    sha256 = "23ef6206a801667fd19cd8105ff73dfdc90d97312fbea7c7fa350d380a1417d2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.7+0/aws_c_event_stream.v0.5.7.aarch64-unknown-freebsd.tar.gz"
[[aws_c_event_stream]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1f59ebd4646bcf93fd295e323b2c96e71008a5ff"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "e9e8f8a4c90d028381ee3a0c8f0027821ab437dbecb14024210eccc63013e237"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.7+0/aws_c_event_stream.v0.5.7.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a3cc86f5d29bff417856721300c28391059c4894"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "37631cb601773028c40f251211b498ded14ade21ee4919b5c8a6957114eba822"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.7+0/aws_c_event_stream.v0.5.7.armv6l-linux-musleabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a4e1f859bc5c72d638bab36206dbbf0f59e6b88d"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "cb3e33c39c33aefca51615ac42bc5f3c92c3726a17e8300e3104ac3664852ed3"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.7+0/aws_c_event_stream.v0.5.7.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b81580f7b93efe2e05c1a77f57a475647269cafe"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "fb393e171347238596802fa14028891679c2da3ef7d931ea4843e223f16fa167"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.7+0/aws_c_event_stream.v0.5.7.armv7l-linux-musleabihf.tar.gz"
[[aws_c_event_stream]]
arch = "i686"
git-tree-sha1 = "a7142d6c99dacf411d268d70f0a9c457f49e1847"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "ac1d1b2434d8ef4f87188b1726c38a138302266fffe4a163811cd48e660717da"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.7+0/aws_c_event_stream.v0.5.7.i686-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "i686"
git-tree-sha1 = "e753a4e0cdec70746b4c30ddb98a41612e5729b7"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "785100c316db6c8072af5b2f6316163a4f6ce24783823f0d3beaf2fd07ce3654"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.7+0/aws_c_event_stream.v0.5.7.i686-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "powerpc64le"
git-tree-sha1 = "57d07e08b5c2a36d3faec15ed71ca65e3d3b1663"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "9696a23aec6f3058adca29af5be23fe75abc7a1e880c28906cd150534f195c1d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.7+0/aws_c_event_stream.v0.5.7.powerpc64le-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "riscv64"
git-tree-sha1 = "a994b9ffd9a890a12ae9282469abf1370b3e81dc"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "8b044c481027e9ee9c78a30b0428eec3c945294f67a79b6e5af1a00c7a10b507"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.7+0/aws_c_event_stream.v0.5.7.riscv64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "4a7e277e537c8fc286e06a5ffbb4c90f3eb89b8f"
os = "macos"

    [[aws_c_event_stream.download]]
    sha256 = "bbda1c495b4deaf8dff023bccbf5de00ce993e9d5c3c83e4ed12928aff475d6a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.7+0/aws_c_event_stream.v0.5.7.x86_64-apple-darwin.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "564d9ee15227a202831dc8a28f0a52377bf91017"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "15bdbc44dcd1005097155959c55bbd6dee971df0e9cf59b2ee2e524db38894ec"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.7+0/aws_c_event_stream.v0.5.7.x86_64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "e1083581114c1ad80e68cda355fbccef8a6b7fac"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "f74ca289474167cbb4ea8e881d386bff9a136f51cc7cecf731715d3890008935"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.7+0/aws_c_event_stream.v0.5.7.x86_64-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "0f41479d2d94251f916bccf40379ce2dc686f805"
os = "freebsd"

    [[aws_c_event_stream.download]]
    sha256 = "1045d41d3a76abf4d2c0d142c5bf7a209b8ff96ac2623cccff60488c6d733489"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.7+0/aws_c_event_stream.v0.5.7.x86_64-unknown-freebsd.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "cb40c62d4e7805153786e6cc0ed783d7955485b2"
os = "windows"

    [[aws_c_event_stream.download]]
    sha256 = "a13ecab0bafa35e23759893a48095055fc754e672ec960700f6783a9f28d7e73"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.5.7+0/aws_c_event_stream.v0.5.7.x86_64-w64-mingw32.tar.gz"
