[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "816f2d233d6c58d8fb9cc02d453363e596d3095d"
os = "macos"

    [[aws_c_event_stream.download]]
    sha256 = "4b8502915291c4ec828d613e91c1790c9264aa6dbd807183ff2acb37174e9b7c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.4.2+0/aws_c_event_stream.v0.4.2.aarch64-apple-darwin.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "d5f5e6fd9e56f65b2aff3dfb7695372e2098c544"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "387d38260f458c2956e88de9297936fc5898a2682aaff08fd47683f41bfd2344"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.4.2+0/aws_c_event_stream.v0.4.2.aarch64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "aarch64"
git-tree-sha1 = "69f87573ac1e88da3b7cde47ad838b64fe142fd6"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "41521c882109c0bf6babac787b97449d1d75b8273b9dcaeb0785312dc165bbfb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.4.2+0/aws_c_event_stream.v0.4.2.aarch64-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a42736180e88a9d6f8eacc7b035d29db62bba282"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "f56853a6aad0faf4d62b06a9110d1bd388c1f0716605ba77d889583790b3cf3e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.4.2+0/aws_c_event_stream.v0.4.2.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a17cca35c993f20a7c6e5f9d734023c98e32550c"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "5b0d4183f931780a207e87e76abeb9f31fdf28c5c2d72323215bd36b06e106a9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.4.2+0/aws_c_event_stream.v0.4.2.armv6l-linux-musleabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f8a7bd02a848bb59e7cba4882d90c2985f7b1441"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "cd221bc5d5f7fe71b88b37becfd3c17bb05fe4482d3d2dd9f2ee3263b70281bc"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.4.2+0/aws_c_event_stream.v0.4.2.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_event_stream]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cb898b9ec7b8b5bb5190b626de2aa446b39af11c"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "9de5001283ad7f7efff5f9accfeaed9a93f69c25e0223a4f1af7de1b28fd2d68"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.4.2+0/aws_c_event_stream.v0.4.2.armv7l-linux-musleabihf.tar.gz"
[[aws_c_event_stream]]
arch = "i686"
git-tree-sha1 = "034bc8e014258fbfd2808e902866657daeadc78a"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "3d390d377e1fe47847638aa5561ce4d8cc9b1a6177833dcb229e35473d891f38"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.4.2+0/aws_c_event_stream.v0.4.2.i686-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "i686"
git-tree-sha1 = "828b5722c2a8413ad797cbbf6607360763967396"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "cab72af1b1563a33281f34979c240dab98ce1bbba3b38d97f252c81ca7f1ae93"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.4.2+0/aws_c_event_stream.v0.4.2.i686-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "powerpc64le"
git-tree-sha1 = "43d97b3943455a065607332d3f1e4412cbd4dc74"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "12c8a936aa66c5676884b2cd0fdc99d2516ca36956cc32a938969f9bf3285e9d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.4.2+0/aws_c_event_stream.v0.4.2.powerpc64le-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "17465e55ba033f6c0833428e6af4cd6cb010140e"
os = "macos"

    [[aws_c_event_stream.download]]
    sha256 = "9c982276f581c06f92252c56cfe33ab9f85055cb511f0ddb97e97731edd2aac8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.4.2+0/aws_c_event_stream.v0.4.2.x86_64-apple-darwin.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "44b671dfbe1fe4a3c463b2793263823ffc6f04ed"
libc = "glibc"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "a0b6fa7920897f6e366a68b4d880ebf2f246e0baab53d5bd17af539ffc2c7152"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.4.2+0/aws_c_event_stream.v0.4.2.x86_64-linux-gnu.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "d1a47fa8a8c5e1628d305a7e66b6c298476c5fa6"
libc = "musl"
os = "linux"

    [[aws_c_event_stream.download]]
    sha256 = "cc038ca7690823d429574b889072688cb7edad0b114dd71260311821ec149ee7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.4.2+0/aws_c_event_stream.v0.4.2.x86_64-linux-musl.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "0114468bee1e02a6a5acc8d6f26f4eadbe37482e"
os = "freebsd"

    [[aws_c_event_stream.download]]
    sha256 = "280983f27cba86131e8c5b2f2ffb5b1016873009445477c33ca2cce1231d15af"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.4.2+0/aws_c_event_stream.v0.4.2.x86_64-unknown-freebsd.tar.gz"
[[aws_c_event_stream]]
arch = "x86_64"
git-tree-sha1 = "73a291ab88ab23528fb8003a451a6b991fa0a435"
os = "windows"

    [[aws_c_event_stream.download]]
    sha256 = "5e1238bb973335d3397b88b3ef77b81eda6cdfa1490b502d7b17a3ea404a2dd3"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_event_stream_jll.jl/releases/download/aws_c_event_stream-v0.4.2+0/aws_c_event_stream.v0.4.2.x86_64-w64-mingw32.tar.gz"
